import Head from 'next/head'
import { Inter } from 'next/font/google'
import ConnectWallet from '@/components/Wallet/ConnectWallet'
import WalletOverview from '@/components/Wallet/WalletOverview'
import Account from '@/components/Home/Account'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>0x-wallet</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <ConnectWallet />
                <WalletOverview />
                <Account />
            </main>
        </>
    )
}
